// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesCssModule {
  export interface IStylesCss {
    bigImg: string
    card: string
    controls: string
    cursorCrosshair: string
    hovered: string
    image: string
    imgContainer: string
    listHeader: string
    listItem: string
    point: string
    pulse: string
  }
}

declare const StylesCssModule: StylesCssModule.IStylesCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesCssModule.IStylesCss
}

export = StylesCssModule
