// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesCssNamespace {
  export interface IStylesCss {
    body: string
    controls: string
    danger: string
    header: string
    modal: string
    modalHeaderClose: string
    modalScroll: string
    overlay: string
    primary: string
  }
}

declare const StylesCssModule: StylesCssNamespace.IStylesCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesCssNamespace.IStylesCss
}

export = StylesCssModule
