// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesCssNamespace {
  export interface IStylesCss {
    header: string
    left: string
    menuBtn: string
    title: string
  }
}

declare const StylesCssModule: StylesCssNamespace.IStylesCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesCssNamespace.IStylesCss
}

export = StylesCssModule
